FROM golang:1.17 AS build

WORKDIR /
ENV GO111MODULE=on
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build

FROM ubuntu:21.04
COPY --from=build ./k8s-proxy-image-swapper .
ENTRYPOINT [ "sleep 1000000" ]
