---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: k8s-pisw
spec:
  type: ClusterIP
  selector:
    app: k8s-proxy-image-swapper-webhook
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
